version: '3.9'

services:
  markhor_slam:
    command: roslaunch markhor_slam markhor_slam.launch
    image: ghcr.io/clubcapra/markhor/markhor:latest
    network_mode: host
    privileged: true
    
  markhor_navigation:
    command: roslaunch markhor_navigation markhor_nav.launch
    image: ghcr.io/clubcapra/markhor/markhor:latest
    network_mode: host
    privileged: true
    depends_on:
      - markhor_slam
