# bridge noetic to foxy
# noetic can communicate with melodic (markhor)
# foxy can communicate with humble
version: '3.9'

services:
  ros1_bridge:
    image: ros:foxy-ros1-bridge-focal
    container_name: ros1_bridge
    network_mode: host
    environment:
      ROS_MASTER_URI: http://localhost:11311
      ROS2_MASTER_URI: http://localhost:11311
    command: >
      bash -c "
        source /opt/ros/foxy/setup.bash;
        source /opt/ros/noetic/setup.bash;
        ros2 run ros1_bridge dynamic_bridge --bridge-all-topics
      "
  
  ros2_template:
    build :
      context: ./docker
      dockerfile: ros2.Dockerfile
    container_name: ros2_template
    network_mode: host
    command: >
      bash -c "
        ros2 topic echo /joy sensor_msgs/Joy
      "
    depends_on:
      - ros1_bridge