version: '3.9'

services:
  markhor_gazebo:
    command: roslaunch markhor_gazebo test_world.launch
    image: ghcr.io/clubcapra/markhor/markhor:latest
    network_mode: host
  
  ros_slam:
    command: roslaunch markhor_slam markhor_slam.launch
    image : ghcr.io/clubcapra/markhor/markhor:latest
    network_mode: host
  
  ros_navigation:
    command: roslaunch markhor_navigation markhor_nav.launch
    image : ghcr.io/clubcapra/markhor/markhor:latest
    network_mode: host