markhor:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  flipper_fl_effort_controller:
    type: effort_controllers/JointPositionController
    joint: flipper_fl_j
    pid: {p: 100.0, i: 0.01, d: 10.0}