markhor:
  flippers:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50  
    
    # Position Controllers ---------------------------------------
    flipper_fl_position_controller:
      type: position_controllers/JointPositionController
      joint: flipper_fl_j
      pid: {p: 0.0, i: 0.0, d: 0.0}
    flipper_fr_position_controller:
      type: position_controllers/JointPositionController
      joint: flipper_fr_j
      pid: {p: 0.0, i: 0.0, d: 0.0}
    flipper_rl_position_controller:
      type: position_controllers/JointPositionController
      joint: flipper_rl_j
      pid: {p: 0.0, i: 0.0, d: 0.0}
    flipper_rr_position_controller:
      type: position_controllers/JointPositionController
      joint: flipper_rr_j
      pid: {p: 0.0, i: 0.0, d: 0.0}

