twist_mux:
  topics:
    - name    : joy_cmd_vel
      topic   : /markhor/joy/cmd_vel
      timeout : 0.5
      priority: 2
    - name    : move_base_cmd_vel
      topic   : /move_base/cmd_vel
      timeout : 0.5
      priority: 1
