# Basic parameters
frequency: 50
sensor_timeout: 0.1
two_d_mode: true
transform_time_offset: 0.0
transform_timeout: 0.0
print_diagnostics: true
publish_acceleration: false

# Whether to broadcast the transformation between the 'map' and 'odom_filtered' frames
publish_tf: false

# The frame to use for publishing the transformed odometry data
map_frame: map

# The frame to use as the parent of the 'odom_filtered' frame
odom_frame: odom

# The frame to use as the child of the 'odom_filtered' frame
base_link_frame: base_link

# The frame to use as the parent of the 'base_link' frame
world_frame: odom

# Configuration for the robot_localization package using
# /markhor/tracks/diff_drive_controller/odom for odometry and
# VectorNav IMU

# Odometry topic configuration
odom0: /markhor/tracks/diff_drive_controller/odom
odom0_config: [
    false, # X
    false, # Y
    false, # Z
    false, # Roll
    false, # Pitch
    false, # Yaw
    true, # X velocity
    false, # Y velocity
    false, # Z velocity
    false, # Roll velocity
    false, # Pitch velocity
    true, # Yaw velocity
    false, # X acceleration
    false, # Y acceleration
    false, # Z acceleration
  ]

odom0_differential: false
odom0_relative: true
odom0_queue_size: 10
odom0_pose_rejection_threshold: 2
odom0_twist_rejection_threshold: 2

# IMU topic configuration
imu0: /vectornav/IMU
imu0_config: [
    false, # X
    false, # Y
    false, # Z
    false, # Roll
    false, # Pitch
    false, # Yaw
    false, # X velocity
    false, # Y velocity
    false, # Z velocity
    false, # Roll velocity
    false, # Pitch velocity
    false, # aw velocity
    false, # X acceleration
    false, # Y acceleration
    false, # Z acceleration
  ]

imu0_queue_size: 5
imu0_nodelay: true
imu0_differential: false
imu0_relative: false
imu0_remove_gravitational_acceleration: true

# Process noise covariance
process_noise_covariance:
  [
    1e-3,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-3,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-6,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-6,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-6,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-6,
  ]
