name: Docker Image CI

on:
  push:
    branches: [ "ftr/docker" ]
  pull_request:
    branches: [ "ftr/docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag markhorgithub:$(date +%s)
