name: Docker Image CI

on:
  push:
    paths:
      - '/Dockerfile.base'
      - '/Dockerfile.markhor'

jobs:
  build_base:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Dockerfile.base')
    
    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.base
        push: true
        tags: ghcr.io/${{ github.repository }}/base:${{ github.sha }}

  build_markhor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.markhor
        push: true
        tags: ghcr.io/${{ github.repository }}/markhor:${{ github.sha }}
